alias reload!='. ~/.zshrc'
alias ls='ls --color'
alias cdd='cd ..'
alias fuck='sudo $(history -p \!\!)'
alias emacs='emacs -nw'
alias ungz='tar -xvf'
alias unbz='tar -xvjf'
alias imgcompress='convert -strip -interlace Plane -gaussian-blur 0.05 -quality 85%'
